### ISSUE TITLE
quick select FB and error options appear hardcoded

### ISSUE THREAD

**Issue by ggggggggg** [usnistgov/microscope#19]
For example if I run 1 column by 4 rows, I would expect to have only one option in the quick select drop downs, for col 0. Instead I have 4*8 options.

**Comment by joefowler** [comment]
Yeah, I have an old to-do list item concerning the broader question: how can we make Microscope know about the number of and names of channels? We should sit down and discuss someday.

Basically it now passively listens to whatever complete pulse records are published on the relevant socket. There is no Q&A for the Microscope process to quiz the Dastard server about this stuff. Options might include:

1. Condense the info to such a small amount that we can afford to include it in every single published record's header. Somehow say "the pattern is {Err*,Ch*} repeating 224 times, and this is split into 8 columns of 28 rows", or whatever.
1. Send a separate message containing that information. Maybe it comes immediately before a pulse record, unless it has been sent in the last N seconds. This would, of course, impose a delay of up to N seconds on any plotting, which sucks unless N = 1.
1. Maybe it's as simple as saying "yes/no this kind of source includes an error channel, and the array is 8x28". That's quite cheap to include in every header: 1 bool and 2 integers.  But it's also a lot less flexible. 
1. If we add the text "rows" and "columns" to the header, then it's easy to generalize the previous to uMUX, because it would maybe be "resonators" x "sub-bands".
1. Or finally, there could just be a source-type code. TDM implies rows x columns with alternating err/fb; uMUX implies resonators x sub-bands without error channels; and we add to this as needed.

Then, of course, we'd use that information to stop hard-coding the quick-select choices, to disable the error channels for uMUX sources, etc.

**Comment by joefowler** [comment]
See [dastard issue 114](https://github.com/usnistgov/dastard/issues/114) for discussion of proposals about how to do this.

**Comment by joefowler** [comment]
I think we agreed to a model where microscope only is changed. It uses command-line arguments to specify several things:

* Whether it's reading a TDM source that produces error/FB channels alternating. (Default: yes, I think).
* How many rows and columns there are in the TDM system (no defaults--you have to enter these numbers).
* (Optional) What text to have in the window's title bar (Default: Microscope).
* What port to listen to.

```
./microscope [--title="Put this on the window title bar"] [--no-error-channel] [--rname=Rows] [--cname=Cols] -r28 -c8 tcp://localhost:5502/
```

This will require adding in a full-featured command-line parser. Ugh. It will be worth it, though.
